### ISSUE TITLE
cursor in highlighted text

### ISSUE THREAD

**Issue by DutchPete** [tu2-atmanand/RoseRed-ObsidianTheme#1]
1st of all a compliment about a nice theme, well done!
2nd, it still is not in the Community market place.
3rd, the topic of this is issue, is as follows.

When `==some text is highlighted==` and you want to edit any of that text, it is impossible to move the cursor to the exact spot within that highlighted section, the cursor remains stuck at the 1st `=`.

So, in order to edit the text, you have to remove the highlight and reinstate it after the edit.

**Comment by tu2-atmanand** [comment]
Thank for bringing the issue to my notice, i wasnt using highlighting feature, hence didnt noticed that. But actually what happening is, since the cursor color is white and when you enter in the highlighted text region which is yellow, the cursor becomes hardly visibly, but still its there, if you notice closely, its blinks.

But yes, its an issue, ill try to solve it using changing the cursor color to darker, when it enters this region. If there is any other better solution, i would like to hear it as well.

Thank you.

**Comment by DutchPete** [comment]
Thanks for your quick reply, 
I am surprised you did not look at the highlighting feature because highlighted text color changes from white to grey, which I thought you had done intentionally. It will be good to change the cursor color accordingly.

**Comment by tu2-atmanand** [comment]
The issue has been resolved in the new version released : V0.0.3.
Closing this issue, I hope the new version has resolved the issue.

**Comment by DutchPete** [comment]
Sorry to disappoint you, but there is literally no change on my side.

**Comment by tu2-atmanand** [comment]
Is it still haven't been updated even after updating your theme ?

Kindly check if your installed version of theme is : Currently Installed : 0.0.3  as per below image 
![image](https://github.com/user-attachments/assets/5b3ba16c-d42b-49c4-a11e-95d7be6429bb)


It has been updated on my system : 
![image](https://github.com/user-attachments/assets/2fa3e464-aeba-4ff2-86c7-c78a5c6c90c2)

**Comment by tu2-atmanand** [comment]
Also my workflow for new release is failing for some reason, i am wondering why its happening, ill see

**Comment by DutchPete** [comment]
Yes, I have installed 0.03

![image](https://github.com/user-attachments/assets/422a892f-9eec-44d1-b177-4adde10195f3)

I reloaded Obsidian, then even closed and relaunched it. No change.
FYI, I have never had this issue with other themes, and still don't.

**Comment by tu2-atmanand** [comment]
I have made few changes and have globalized the color for the cursor. Along with that few more changes have also been made to table and dataview colors and a new version 0.0.4 has been released.
Let me know if the issue of cursor in highlighted region have been resolved now.

Also can you tell me which operating system you are using so i can test it on a similar system.

**Comment by DutchPete** [comment]
Yes, that works:

![image](https://github.com/user-attachments/assets/a7038fe0-9331-4cf3-9f47-52b87b9d1c89)

I am on Linux LMDE 6 Faye.

**Comment by tu2-atmanand** [comment]
That's nice to know.. 
Well, thank you so much for bringing the issue to my notice. Improvement/Advancement in softwares happens because of the collaboration and contributions from people like you. Glad to have you in my network.

Feel free to create other issues if there are any improvements required, ill try my best to achieve the same.

Thank You!

**Comment by DutchPete** [comment]
Thank you for a beautiful theme. For a long time now I have been looking for a theme that I can use comfortably during the day and the evening.

Withh dark themes you often have to strain your eyes during the day to be able to read the screen.

Light themes are usually no good either because they are too bright during the evening, so ideally you would need one that is colored the right way with the right colors.

Red Rose, although a dark theme, is a theme you can comfortably use during the day, it has the right combination of color (not a standard, horrible, hard red) and the subtle color gradation from top right to bottom left. Well done.
